import Footer from 'components/footer'
import Navbar from 'components/navbar'

import '../assets/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className='flex min-h-screen flex-col bg-white'>
        <Navbar />
        <main className='flex-grow p-4'>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
